name: pyright_black_lint_check
on: 
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8' ]
        
  black:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8' ]

    name: black check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel black
          python -m pip install -U -r requirements.txt
      - name: Run black
        run: python -m black --check --verbose *
