name: greet_new_contributors
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    name: Greet new contributors
    steps:
      - uses: actions/checkout@v3

      - name: Get sender's login
        id: sender
        run: echo "The sender of the event is ${{ github.event.sender.login }}"

      - name: Check if sender has previously contributed
        id: contribution-check
        run: |
          git log --author="${{ steps.sender.outputs.login }}" --oneline HEAD
          if [[ $? -ne 0 ]]; then
            echo "This is the first contribution from this user."
          else
            echo "This user has previously contributed."
            exit 1
          fi

      - name: Post greeting message
        uses: peter-evans/create-or-update-issue-comment@v2
        if: github.event.sender.login != 'actions'
        with:
          body: |
            Hi @${{ steps.sender.outputs.login }}, thanks for opening an issue or pull request! We appreciate your contribution to the project. Let us know if you have any questions or need help getting started.
          issue-number: ${{ github.event.issue.number }}
          repository-dispatch: false
